


name: test_githubactions

on:
  push:
    branches:
      - main

jobs:
  id_sample:
    name: sample_github_actions
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: sift_system/original_product_second/backend
    steps: 

      - name: start github actions!
        run: echo start github actions
    

